services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://balajikundrapu:Balaji123456@cluster0.xgh87ph.mongodb.net/mini-compliance-tracker?retryWrites=true&w=majority&appName=Cluster0
      - PORT=5000

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
